### ISSUE TITLE
0.42 does not support Lenovo Thinkpad T460p

### ISSUE THREAD

**Issue by doofy** [evgeni/tp_smapi#24]
loading thinkpad_ec throws:

[ 3586.118792] thinkpad_ec: thinkpad_ec_request_row: arg0 rejected: (0x01:0x00)->0x00
[ 3586.118795] thinkpad_ec: thinkpad_ec_read_row: failed requesting row: (0x01:0x00)->0xfffffffb
[ 3586.118796] thinkpad_ec: initial ec test failed

I do not have the time at the moment to look deeper into this but I could supply you with all the info you need about the T460p.

**Comment by evgeni** [comment]
Hi,

I am sorry, but the T460p will never be supported as it does not have the same SMAPI interface anymore.
