### ISSUE TITLE
Problems with kernel 4.7.x

### ISSUE THREAD

**Issue by ray65536** [evgeni/tp_smapi#25]
Hi! Please, consider to include patch, mentioned [here](https://bugs.launchpad.net/ubuntu/+source/tp-smapi/+bug/1606447) 

tp_smapi really not working on the same hardware (E430) after kernel update (works well with previous version, and with patched version)

**Comment by evgeni** [comment]
Hi,

nope, the right patch was applied in https://github.com/evgeni/tp_smapi/commit/8f40fcf3d9a4bfb9c3dae1caa2107ea3a367a609 about two years ago :)

Greets
Evgeni
