### ISSUE TITLE
Cannot load on L460

### ISSUE THREAD

**Issue by py-crash** [evgeni/tp_smapi#28]
Hi, I'm having issues on my Lenovo Thinkpad L460, installed on archlinux from the community repo:

    $ sudo modprobe tp_smapi 

    modprobe: ERROR: could not insert 'tp_smapi': No such device or address

**Comment by evgeni** [comment]
Hi,

L460 is not supported and will never be. Lenovo changed the interface starting with the SandyBridge models and tp-smapi cannot work with the new interface.

You can (maybe) control the battery using acpi-call, see http://linrunner.de/en/tlp/docs/tlp-faq.html and http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html

**Comment by py-crash** [comment]
I tried the  acpi-call worked just fine. Thanks!
