### ISSUE TITLE
Linux v4.15: init_timer() interface removed

### ISSUE THREAD

**Issue by hessophanes** [evgeni/tp_smapi#31]
This requires a small change in hdaps.c - see [patch](http://www.sec.t-labs.tu-berlin.de/~jan/0001-Adapt-HDAPS-driver-to-use-the-new-timer_setup-interf.patch).

**Comment by riesebie** [comment]
The patch mentioned above seems to solve [Debian bug #884973](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884973).

**Comment by evgeni** [comment]
Thanks!
